# Generated by Django 4.0.4 on 2022-05-30 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 30), verbose_name='Date'),
        ),
    ]
