# Generated by Django 4.0.4 on 2022-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, default='', max_length=90, verbose_name='Description'),
        ),
    ]
