# Generated by Django 4.0.4 on 2022-06-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_expense_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['type'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='MoneyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=90, verbose_name='Description')),
                ('money', models.IntegerField(verbose_name='Pool of Money')),
                ('expenses', models.ManyToManyField(to='App.expense')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
