# Generated by Django 4.0.4 on 2022-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_moneypool_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneypool',
            name='expenses',
            field=models.ManyToManyField(blank=True, to='App.expense'),
        ),
    ]
