FROM python:3.12.4

WORKDIR /MoneyGMA

ENV PYTHONUNBUFFERED=1
ENV MGMA_DB=MGMA_DB
ENV MGMA_PASS=MGMA_PASS
ENV MGMA_USER=MGMA_USER
ENV MGMA_DEBUG=MGMA_DEBUG
ENV MGMA_KEY=MGMA_KEY

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN chmod +x deployment.d/simple_start.sh

EXPOSE 8122

#CMD ["gunicorn","--bind", ":8122", "MoneyGMA/MoneyGMA.wsgi:application"]
CMD ["deployment.d/simple_start.sh"]
